apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-qkmd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-qkmd
    app.kubernetes.io/part-of: test-app-appx
  name: test-component-qkmd
  namespace: build-e2e-lkun-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-qkmd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-qkmd
    spec:
      containers:
      - image: quay.io/susdas/test-images:d6eaaef78f5e411db195c6f2dc45d891
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
